version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password1234!
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: